"""
Django settings for vet_reservation project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from httpcore import MockBackend

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Redirige Django vers notre page de login personnalisée
LOGIN_URL = 'appointments:login'

# Page de redirection après login (optionnel)
#LOGIN_REDIRECT_URL = 'appointments:appointment_list'
LOGIN_REDIRECT_URL = 'appointments:home'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # For testing
ACCOUNT_AUTHENTICATION_METHOD = 'email'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create user on first Google login
# Un email = un seul compte
ACCOUNT_UNIQUE_EMAIL = True
# Pour envoyer les emails dans la console (utile en développement)



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jablounomaima2@gmail.com'
EMAIL_HOST_PASSWORD = 'swcj yemd upjl tgtj'    # Utilise un "App Password" si 2FA activé
DEFAULT_FROM_EMAIL = 'noreply@tonsite.com'







# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i09%=+^f1i$%sr_+t3tw_13pg9%)9*qj)h50-v@h=sikbvh)ea'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
SITE_ID = 2

# Application definition

INSTALLED_APPS = [
     'jazzmin',



    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appointments',  # <--- Ajoute cette ligne
    'django_extensions',
    'django.contrib.sites', # pour ajouter framewark sites qui permet a ton application de gérer plusieurs sites web a partir d'un seul base de donne
    


     # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
   
    'allauth.socialaccount.providers.google',  # Pour Google login


     # Required for allauth
     'axes',
    
]

AUTHENTICATION_BACKENDS = [
    'appointments.authentication.EmailBackend',  # ← Backend par email # Connexion locale
    'allauth.account.auth_backends.AuthenticationBackend',  # Connexion sociale
]

# settings.py




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     
    # ✅ Middleware obligatoire pour django-allauth
    'allauth.account.middleware.AccountMiddleware',  # 🔥 À ajouter ici
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',
    


    
]





ROOT_URLCONF = 'vet_reservation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates',          # ← Global templates
            BASE_DIR / 'appointments/templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vet_reservation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / 'static',  # ← Dossier global de static
    BASE_DIR / 'appointments' / 'static',  # ← Static de l'app
]

STATIC_ROOT = BASE_DIR / 'collected_static'  # Utilisé avec collectstatic
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
ACCOUNT_FORMS = {
    'login': 'appointments.forms.CustomLoginForm',
    'signup': 'appointments.forms.CustomSignupForm',  # ← Clé importante
    
}


class EmailBackend(MockBackend):
    """
    Permet de se connecter avec l'email au lieu du username
    """
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = user.objects.get(email=username)
        except user.DoesNotExist:
            return None
        if user.check_password(password) and self.user_can_authenticate(user):
            return user
        return None
    





# === Configuration de django-axes ===
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = timedelta(minutes=2)  # Blocage de 2 minutes