# Generated by Django 5.2.4 on 2025-09-04 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('species', models.CharField(choices=[('dog', 'Chien'), ('cat', 'Chat'), ('other', 'Autre')], max_length=10, verbose_name='Espèce')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Race')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Consultation'), ('deworming', 'Traitement antiparasitaire'), ('surgery', 'Chirurgie'), ('dental', 'Soins dentaires')], max_length=20, verbose_name='Service')),
                ('date', models.DateField(verbose_name='Date du rendez-vous')),
                ('time', models.TimeField(verbose_name='Heure du rendez-vous')),
                ('phone', models.CharField(help_text='Ex: +212 6 12 34 56 78', max_length=15, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Refusé')], default='pending', max_length=10, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text="Message envoyé à l'utilisateur si le RDV est refusé", null=True, verbose_name='Notes admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.pet', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-created_at'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
